name: aliyun

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3 # choose your pnpm version
          run_install: true

      - name: Code lint
        run: pnpm lint

      - name: Build (Generate static files)
        run: pnpm run build

      - name: Setup aliyun OSS
        uses: yizhoumo/setup-ossutil@v1
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.AL_KEY_ID }}
          access-key-secret: ${{ secrets.AL_KEY_SECRET }}

      - name: Upload files to OSS
        run: |
          ossutil rm -f oss://zq-luojia-tactic/ -r
          ossutil cp -rf dist oss://zq-luojia-tactic/
          ossutil set-meta oss://zq-luojia-tactic/ Cache-Control:no-cache --include "*.html" -r

      - name: Refresh CDN
        uses: visionwx/ali-cdn-refresh@v0.1.1
        with:
          accessKeyId: ${{ secrets.AL_KEY_ID }}
          accessKeySecret: ${{ secrets.AL_KEY_SECRET }}
          type: Directory
          path: https://luojiatactic.ziqiang.net.cn/

      # - name: Configure obsutil
      #   run: |
      #     wget https://obs-community.obs.cn-north-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz
      #     tar -xzf obsutil_linux_amd64.tar.gz
      #     sudo mv obsutil_linux_amd64_*/obsutil /usr/local/bin/
      #     obsutil config -i=${{ secrets.HUAWEI_OBS_AK }} -k=${{ secrets.HUAWEI_OBS_SK }} -e=${{ secrets.OBS_ENDPOINT }}

      # - name: Upload Files
      #   run: obsutil cp dist/ obs://${{ secrets.OBS_BUCKET_NAME }}/ -f -r -flat